### ISSUE TITLE
Unstable test on CI

### ISSUE THREAD

**Issue by andylokandy** [fast/fastrace#9]
```
thread 'test_macro_properties' panicked at fastrace/tests/lib.rs:756:5:
assertion `left == right` failed
  left: "\nroot []\n    bar_async []\n    foo_async [(\"k1\", \"v1\"), (\"a\", \"argument a is 1\"), (\"b\", \"Bar\"), (\"escaped1\", \"Bar{}\"), (\"escaped2\", \"{ \\\"a\\\": \\\"b\\\"}\")]\n"
 right: "\nroot []\n    bar []\n    bar_async []\n    foo [(\"k1\", \"v1\"), (\"a\", \"argument a is 1\"), (\"b\", \"Bar\"), (\"escaped1\", \"Bar{}\"), (\"escaped2\", \"{ \\\"a\\\": \\\"b\\\"}\")]\n    foo_async [(\"k1\", \"v1\"), (\"a\", \"argument a is 1\"), (\"b\", \"Bar\"), (\"escaped1\", \"Bar{}\"), (\"escaped2\", \"{ \\\"a\\\": \\\"b\\\"}\")]\n"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/core/src/panicking.rs:365:5
   4: lib::test_macro_properties::{{closure}}
             at ./tests/lib.rs:756:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/core/src/ops/function.rs:250:5
   6: serial_test::serial_code_lock::local_serial_core
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serial_test-3.1.1/src/serial_code_lock.rs:36:5
   7: lib::test_macro_properties
             at ./tests/lib.rs:697:1
   8: lib::test_macro_properties::{{closure}}
             at ./tests/lib.rs:698:27
   9: core::ops::function::FnOnce::call_once
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/24d2ac0b56fcbde13d827745f66e73efb1e17156/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_macro_properties ... FAILED

failures:

failures:
    test_macro_properties

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.34s
```

https://github.com/fastracelabs/fastrace/pull/1#issuecomment-2230745593

**Comment by andylokandy** [comment]
Seems not reproducible on github action.

**Comment by tisonkun** [comment]
https://github.com/fast/fastrace/actions/runs/11733199886/job/32686969382

@andylokandy seems the failure cause is that we catch only `async fn`'s trace but not `fn`'s trace. Any thoughts on how to investigate deeper?

**Comment by andylokandy** [comment]
The hardest part is we cannot reproduce it locally...

**Comment by andylokandy** [comment]
maybe related to https://github.com/mgeier/rtrb/issues/114

**Comment by tisonkun** [comment]
Resolved by https://github.com/fast/fastrace/pull/90?

**Comment by andylokandy** [comment]
Since migrated to nextest, it has never been observed.
